// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {license} from '../models';
import {main} from '../models';
import {db} from '../models';

export function ActivateLicense(arg1:string):Promise<license.Status>;

export function AddAccountsToPool(arg1:string,arg2:Array<string>):Promise<void>;

export function ArchiveAccounts(arg1:Array<string>,arg2:boolean):Promise<void>;

export function CreateAccount(arg1:main.AccountInput):Promise<db.MetaAdAccount>;

export function CreateCreative(arg1:main.CreativeInput):Promise<db.Creative>;

export function CreateHeadlineSet(arg1:main.HeadlineSetInput):Promise<db.HeadlineSet>;

export function CreateLaunchJob(arg1:main.LaunchInput):Promise<main.LaunchResult>;

export function CreatePool(arg1:main.PoolInput):Promise<db.AccountPool>;

export function CreateTemplate(arg1:main.TemplateInput):Promise<db.CampaignTemplate>;

export function DeleteCreative(arg1:string):Promise<void>;

export function DeleteHeadlineSet(arg1:string):Promise<void>;

export function DeletePool(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function GetAccounts(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.AccountsResult>;

export function GetAuditLogs(arg1:number,arg2:number):Promise<Array<db.AuditLog>>;

export function GetCreatives(arg1:string,arg2:string):Promise<main.CreativesResult>;

export function GetCurrentUser():Promise<main.AuthResponse>;

export function GetHeadlineSets():Promise<main.HeadlineSetsResult>;

export function GetHealthHistory(arg1:string,arg2:number):Promise<Array<db.AccountHealthCheck>>;

export function GetLaunchJob(arg1:string):Promise<db.LaunchJob>;

export function GetLaunchJobs(arg1:number):Promise<Array<db.LaunchJob>>;

export function GetLicenseStatus():Promise<license.Status>;

export function GetPools():Promise<main.PoolsResult>;

export function GetTemplates():Promise<main.TemplatesResult>;

export function IsSetup():Promise<boolean>;

export function KeitaroSync(arg1:string,arg2:string,arg3:string,arg4:string,arg5:any):Promise<db.HeadlineSet>;

export function Logout():Promise<void>;

export function MockImportAccounts(arg1:number):Promise<number>;

export function MockSyncAccount(arg1:string):Promise<void>;

export function OpenBillingPage():Promise<void>;

export function RemoveAccountFromPool(arg1:string,arg2:string):Promise<void>;

export function RunBulkHealthCheck(arg1:Array<string>):Promise<Array<main.HealthResult>>;

export function RunHealthCheck(arg1:string):Promise<main.HealthResult>;

export function StartLoginFlow():Promise<main.LoginFlowResponse>;

export function UpdateAccount(arg1:string,arg2:main.AccountInput):Promise<db.MetaAdAccount>;

export function CheckForUpdate():Promise<any>;

export function OpenReleasePage():Promise<void>;

export function GetVersion():Promise<string>;

export function StartUpdate(arg1:string):Promise<void>;
