// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AddAccountsToPool(arg1, arg2) {
  return window['go']['main']['App']['AddAccountsToPool'](arg1, arg2);
}

export function ArchiveAccounts(arg1, arg2) {
  return window['go']['main']['App']['ArchiveAccounts'](arg1, arg2);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateCreative(arg1) {
  return window['go']['main']['App']['CreateCreative'](arg1);
}

export function CreateHeadlineSet(arg1) {
  return window['go']['main']['App']['CreateHeadlineSet'](arg1);
}

export function CreateLaunchJob(arg1) {
  return window['go']['main']['App']['CreateLaunchJob'](arg1);
}

export function CreatePool(arg1) {
  return window['go']['main']['App']['CreatePool'](arg1);
}

export function CreateTemplate(arg1) {
  return window['go']['main']['App']['CreateTemplate'](arg1);
}

export function DeleteCreative(arg1) {
  return window['go']['main']['App']['DeleteCreative'](arg1);
}

export function DeleteHeadlineSet(arg1) {
  return window['go']['main']['App']['DeleteHeadlineSet'](arg1);
}

export function DeletePool(arg1) {
  return window['go']['main']['App']['DeletePool'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function GetAccounts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAccounts'](arg1, arg2, arg3, arg4);
}

export function GetAuditLogs(arg1, arg2) {
  return window['go']['main']['App']['GetAuditLogs'](arg1, arg2);
}

export function GetCreatives(arg1, arg2) {
  return window['go']['main']['App']['GetCreatives'](arg1, arg2);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetHeadlineSets() {
  return window['go']['main']['App']['GetHeadlineSets']();
}

export function GetHealthHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHealthHistory'](arg1, arg2);
}

export function GetLaunchJob(arg1) {
  return window['go']['main']['App']['GetLaunchJob'](arg1);
}

export function GetLaunchJobs(arg1) {
  return window['go']['main']['App']['GetLaunchJobs'](arg1);
}

export function GetLaunchJobsDetailed(arg1) {
  return window['go']['main']['App']['GetLaunchJobsDetailed'](arg1);
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetPools() {
  return window['go']['main']['App']['GetPools']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function IsSetup() {
  return window['go']['main']['App']['IsSetup']();
}

export function KeitaroSync(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['KeitaroSync'](arg1, arg2, arg3, arg4, arg5);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MockImportAccounts(arg1) {
  return window['go']['main']['App']['MockImportAccounts'](arg1);
}

export function MockSyncAccount(arg1) {
  return window['go']['main']['App']['MockSyncAccount'](arg1);
}

export function OpenBillingPage() {
  return window['go']['main']['App']['OpenBillingPage']();
}

export function RemoveAccountFromPool(arg1, arg2) {
  return window['go']['main']['App']['RemoveAccountFromPool'](arg1, arg2);
}

export function RunBulkHealthCheck(arg1) {
  return window['go']['main']['App']['RunBulkHealthCheck'](arg1);
}

export function RunHealthCheck(arg1) {
  return window['go']['main']['App']['RunHealthCheck'](arg1);
}

export function StartLoginFlow() {
  return window['go']['main']['App']['StartLoginFlow']();
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function StartUpdate(arg1) {
  return window['go']['main']['App']['StartUpdate'](arg1);
}

export function CreateGeoRule(arg1) {
  return window['go']['main']['App']['CreateGeoRule'](arg1);
}

export function CreatePauseWindow(arg1) {
  return window['go']['main']['App']['CreatePauseWindow'](arg1);
}

export function DeleteGeoRule(arg1) {
  return window['go']['main']['App']['DeleteGeoRule'](arg1);
}

export function DeletePauseWindow(arg1) {
  return window['go']['main']['App']['DeletePauseWindow'](arg1);
}

export function ForceRunAutocontrol() {
  return window['go']['main']['App']['ForceRunAutocontrol']();
}

export function GetAutocontrolConfig() {
  return window['go']['main']['App']['GetAutocontrolConfig']();
}

export function GetAutocontrolCycleDetail(arg1) {
  return window['go']['main']['App']['GetAutocontrolCycleDetail'](arg1);
}

export function GetAutocontrolCycles(arg1) {
  return window['go']['main']['App']['GetAutocontrolCycles'](arg1);
}

export function GetGeoRules() {
  return window['go']['main']['App']['GetGeoRules']();
}

export function GetPauseWindows() {
  return window['go']['main']['App']['GetPauseWindows']();
}

export function SaveAutocontrolConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAutocontrolConfig'](arg1, arg2);
}

export function UpdateGeoRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateGeoRule'](arg1, arg2);
}

export function CreateScaleRule(arg1) {
  return window['go']['main']['App']['CreateScaleRule'](arg1);
}

export function DeleteScaleRule(arg1) {
  return window['go']['main']['App']['DeleteScaleRule'](arg1);
}

export function ForceRunAutoscale() {
  return window['go']['main']['App']['ForceRunAutoscale']();
}

export function GetAutoscaleConfig() {
  return window['go']['main']['App']['GetAutoscaleConfig']();
}

export function GetAutoscaleCycleDetail(arg1) {
  return window['go']['main']['App']['GetAutoscaleCycleDetail'](arg1);
}

export function GetAutoscaleCycles(arg1) {
  return window['go']['main']['App']['GetAutoscaleCycles'](arg1);
}

export function GetScaleRules() {
  return window['go']['main']['App']['GetScaleRules']();
}

export function SaveAutoscaleConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAutoscaleConfig'](arg1, arg2);
}

export function UpdateScaleRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateScaleRule'](arg1, arg2);
}

export function SendAIMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAIMessage'](arg1, arg2);
}

export function ConfirmAIAction(arg1, arg2) {
  return window['go']['main']['App']['ConfirmAIAction'](arg1, arg2);
}

export function CancelAIAction(arg1) {
  return window['go']['main']['App']['CancelAIAction'](arg1);
}

export function ClearAIConversation(arg1) {
  return window['go']['main']['App']['ClearAIConversation'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function SaveAIConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAIConfig'](arg1, arg2, arg3);
}
